### ISSUE TITLE
duplicate opening "<" for snippet completions

### ISSUE THREAD

**Issue by mrlami** [JasonMortonNZ/bs3-sublime-plugin#99]
Reference snapshot

![bs3-autocomplete-issue](https://cloud.githubusercontent.com/assets/1946090/13514726/6e4632a4-e179-11e5-8fc6-78ec53623400.png)

**Comment by tgirardin** [comment]
I have the same problem.

**Comment by surjithctly** [comment]
+1

**Comment by KumarAditya** [comment]
The issue is happening for me too.

**Comment by mwst** [comment]
And I have the same.

**Comment by mosleimgai** [comment]
step instalation is: before install this plugin, install emmet firstly. it's maybe can solve the problem. and the snippet is not require < again.

**Comment by raedlime** [comment]
The way the problem is solved is shown in one of the closed issues.

Below the answer from JasonMortonNZ:

> Hey guys, I've been stumped by the issue for a long time. There's a setting in Sublime called auto_complete_triggers and by default it's set to "auto_complete_triggers": [ {"selector": "text.html", "characters": "<"} ]. I believe this is the root cause of the '<' remaining.
> 
> Unfortunately I can't find much (any) info in the Sublime docs in order to work out if there's a potential fix for this, but as a solution I updated the setting to this:
> 
> "auto_complete_triggers": [{"selector": "text.html", "characters": "<"},{"selector": "text.html", "characters": "bs3"}]
> 
> Hope that helps guys. Bootstrap 4 snippets is under way an will be released soon :)

**Comment by swirly** [comment]
Same problem for me. The proposition from raedlime is not convenient for me, as it makes the usual completion with <h3 for exemple bieng inactive

Reel problem :(

**Comment by cerealBoxx** [comment]
The solution doesn't work for me. I tried both reinstalling and changing the user preferences as suggested but I still have the issue. Is there another solution?

**Comment by ArunHub** [comment]
For me its working fine...

**Comment by lsvt-olivier** [comment]
Same issue here and outlined solution doesn't work for me either.

**Comment by vdmytrovskyi-lattice** [comment]
+1

**Comment by Pablocgdev** [comment]
I'll add more info, only happens in linux, working as intended in osx and windows.

**Comment by swirly** [comment]
No. It also happens for me on osX.

**Comment by jayleco** [comment]
+1

**Comment by solitud** [comment]
+1

**Comment by tsamridh86** [comment]
Please tell us on details to remove this duplicate < problem, it seriously poses a lot of problems

**Comment by dave-ok** [comment]
SOLVED: DOCUMENTATION ERROR!

Just started using this plugin, had the same issue and found the fix.

Docs incorrectly state "start typing '<bs3' " instead of just "bs3".

**DONT** use the "<" tag when typing, just start typing with "bs...". After confirmation (i.e when u hit ENTER or TAB key depending on ur editor), there should be no extra leading "<" character. 

Problem is "<tabTrigger>" in code snippets do not include leading "<" but starts from "bs...". So e.g if u type "<bs3-col" the plugin will decode only "bs3-col" leaving the "<" character behind.

**Comment by dave-ok** [comment]
Let me/others know if this worked for you

**Comment by Pablocgdev** [comment]
Now it is working as intended, thanks.

**Comment by tsamridh86** [comment]
This only works inside the <? php ?> tags, it does not work when it's outside.
The method you describe is completely ineffective in HTML syntax

**Comment by dave-ok** [comment]
I use this in pure HTML and it works fine. Are u sure u have set ur preferences in sublime text to include: "auto_complete_triggers": [{"selector": "text.html", "characters": "**bs3**"}]. Ensure that u **dont** have any of ur autocomplete triggers set to capture **<bs3** then u shd hav no problems

**Comment by dave-ok** [comment]
Just tried it in CSS and js still good

**Comment by tsamridh86** [comment]
tell me how to check it, i am unable to find that in the sublime text menu, thanks

**Comment by dave-ok** [comment]
Sorry for the late reply.

Goto Preferences->Settings-user and after the last entry place a comma and add like so:
```
"auto_complete_triggers":
	[
		{
			"characters": "bs",
			"selector": "text.html"
		}
	]
```
Save your changes and restart sublime text. Hope this helps

**Comment by tsamridh86** [comment]
Yes, it works, thank you, please include this in the installation documentation also.

**Comment by dave-ok** [comment]
You're welcome will try

**Comment by nir-jas** [comment]
Just Go to Preferences-->Settings-User and Add following line into the settings file.
 "auto_complete_triggers": [ {"selector": "text.html", "characters": "bs"} ]

**Comment by Pablocgdev** [comment]
By setting correctly the filetype this is not needed, I can confirm in OSX, Linux and Windows.
